name: Update personality

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        builder:
          - autoconf
          - meson
    name: Update personality (${{ matrix.builder }})
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1
      - name: Build Dockerfile
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6.9.0
        with:
          context: .
          load: true
          push: false
          tags: buildfarm-client:alpine
      - name: Update OS and Compiler versions
        run: |
          docker run --rm \
            -e ANIMAL=${{ matrix.builder == 'autoconf' && vars.AUTOCONF_ANIMAL || vars.MESON_ANIMAL }} \
            -e SECRET=${{ matrix.builder == 'autoconf' && secrets.AUTOCONF_SECRET || secrets.MESON_SECRET }} \
            --entrypoint "" \
            buildfarm-client:alpine \
              ./update.sh \
              --config ${{ matrix.builder }}.conf
